repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks: [{ id: ruff, args: ["--fix"] }, { id: ruff-format }]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "sqlalchemy>=2.0"
          - "pydantic>=2.7"
          - "types-requests"
          - "boto3-stubs[s3]>=1.34"
          - "types-urllib3"
